#!/usr/bin/env ansible-playbook
---
#==============================================================#
# Init a local yum repo
# all necessary rpm packages are downloaded to accelerate
# cluster initialization, or in case that target machine does
# not have internet access.
#
# RPM packages are downloaded to {{ repo_home }}/{{ repo_name }}.
# And it will skip download if all packages already exists
#
# Local yum repo url: {{ repo_endpoint }}/{{ repo_name }}/
#==============================================================#
# you can invoke repo tasks with infra.yml or install.yml
#
# infra.yml -t repo_url_pkg   # redownload weburl packages
# infra.yml -t repo_boot_pkg  # install bootstrap packages
# infra.yml -t repo_rpm_pkg   # download repo rpm packages
# infra.yml -t repo_create    # create yum repo
# build without check: ./infra.yml -t repo_build -e repo_url_packages=[] -e repo_packages=[]
#
# infra.yml -t repo          # init repo
# infra.yml -t repo_prepare  # use existing repo if exists
# infra.yml -t repo_build    # (re)build local repo
# infra.yml -t repo_nginx    # setup temp nginx server for repo
# infra.yml -t repo_create   # recreate repo
# infra.yml -t repo_upstream # add upstream repo file
# infra.yml -t repo_build   -e repo_url_packages=[]    # build & skip url download
# infra.yml -t repo_build   -e repo_packages=[]        # build & skip rpm download
# infra.yml -t repo_build   -e repo_packages=[] -e repo_url_packages=[]  # skip download
# infra.yml -t repo_url_pkg -e repo_url_packages=[https://github.com/dalibo/pev2/releases/download/v1.8.0/index.html]
# infra.yml -t repo_pkg     -e repo_packages=[xxxx]

#--------------------------------------------------------------#
# 0. Create repo dir?                                 [repo_dir]
#--------------------------------------------------------------#
- name: setup repo dir and file
  tags: repo_dir
  block:

    # create repo directory
    - name: create local repo dir
      tags: repo_dir
      file: path={{ repo_home }}/{{ repo_name }} state=directory mode=0755

    - name: render repo definition file
      tags: repo_file
      copy:
        dest: "{{ repo_home }}/sources.list"
        mode: 0755
        content: |
          deb [trusted=yes] {{ repo_endpoint | replace('${admin_ip}', admin_ip ) }}/{{ repo_name }} ./

#--------------------------------------------------------------#
# 1. Check whether repo exists?                     [repo_check]
#--------------------------------------------------------------#
# check flag file /www/pigsty/repo_complete existence
- name: check local repo exists
  tags: repo_check
  block:
    - name: check local repo exists
      stat: path={{ repo_home }}/{{ repo_name }}/repo_complete
      register: repo_cache
    - name: set repo_exists flag
      set_fact: { repo_exists: "{{ repo_cache.stat.exists }}" }


#--------------------------------------------------------------#
# 2. Use local repo (IF REPO EXISTS)              [repo_prepare]
#--------------------------------------------------------------#
# if local yum cache exists, use it directly, done
- name: setup local repo if exists
  tags: repo_prepare
  when: repo_exists|bool and repo_enabled|bool
  shell: |
    cp {{ repo_home }}/sources.list /etc/apt/sources.list;
    apt-get update;
    apt-get install -y wget nginx sshpass dpkg-dev;
    /bin/true;


#--------------------------------------------------------------#
# 3. Build repo (IF REPO NOT EXISTS)                [repo_build]
#--------------------------------------------------------------#
# if local apt cache not exists, download them and use it, done
- import_tasks: build.yml
  when: repo_enabled|bool and not repo_exists|bool
  tags: repo_build
  ignore_errors: true


#--------------------------------------------------------------#
# 4. Repo Nginx                                     [repo_nginx]
#--------------------------------------------------------------#
# repo nginx will not be created if a nginx server is already running on admin node
# and this temp nginx will be overwritten by role `nginx`.
- import_tasks: nginx.yml
  when: repo_enabled|bool
  tags: repo_nginx


...